[variables]
NIXPACKS_PHP_VERSION = "8.2"
NIXPACKS_NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["php82", "nodejs_18"]

[phases.install]
dependsOn = ["setup"]

[phases.build]
dependsOn = ["install"]
cmds = [
    "chmod +x build.sh start.sh",
    "bash build.sh"
]

[start]
cmd = "bash start.sh"