[variables]
NIXPACKS_PHP_VERSION = "8.2"
NIXPACKS_NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "nodejs_18"]

[phases.build]
cmds = [
    "cd apps/coutellerie-svelte && npm ci && npx svelte-kit sync && npm run build",
    "cd services/coutellerie-laravel && composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "cd services/coutellerie-laravel && php artisan migrate --force --no-interaction && php artisan serve --host=0.0.0.0 --port=$PORT"