[build]
# Use custom build process for monorepo structure
workingDir = "services/coutellerie-laravel"

[deploy]
# Use Procfile for start command  
restartPolicyType = "ON_FAILURE"

# Environment variables
[env]
# Force PHP version to latest supported
PHP_VERSION = "8.3"
# Laravel specific variables will be set in Railway dashboard  
# MySQL variables will be automatically provided by Railway MySQL service