[build]
# Use Railway's automatic PHP/Laravel detection
builder = "Railpack"

[deploy]
# Use Procfile for start command
restartPolicyType = "ON_FAILURE"

# Environment variables  
[env]
# Laravel specific variables will be set in Railway dashboard
# MySQL variables will be automatically provided by Railway MySQL service