[providers]
# Force PHP provider only
providers = ["php"]

[variables]
PHP_VERSION = "8.3"

[build]
# Build commands
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
# Start command
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"